name: Automate Translation

on:
  push:
    branches:
      - main  # Rulează workflow-ul când există modificări pe branch-ul principal

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ia codul din repository-ul tău

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Instalează Python

      - name: Install Translation Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.0-rc1  # Instalare Google Translate API

      - name: Run Translation Script
        run: python translate_script.py  # Rulează scriptul de traducere

