name: Translate HTML Files

on:
  push:
    branches:
      - main  # Rulează automat la push pe branch-ul principal

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Verifică codul din repository

    - name: Set up Python
      uses: actions/setup-python@v3  # Configurează Python
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install googletrans==4.0.0-rc1  # Instalează biblioteca Google Translate

    - name: Translate HTML Files
      run: |
        python translate_script.py  # Rulează scriptul Python pentru traducere

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Translated HTML files"
        git push
